### PR TITLE
fix race warnings and their origins

### LINKED ISSUE #376: take a hard look at the LBA code and redesign where needed
Currently the LBA (lba.go and cache.go) code is pretty fragile, in async environments.

Ideally we want to be able to lock per sector, however:

+ even if we do this in the cache.go code, we are still giving out a pointer to a sector back to the lba code, so this lock within the cache code wouldn't do much;
+ creating a giant map of locks within the lba code (one for each possible index) is insane, so not a good idea at all;
+ ideally we would make sector control itself that it only ever has one owner;

TLDR: ideally LBA code should be thread-safe, and locked as low as a sector level (or perhaps we can even prevent locks at all, by moving to a channel-based strategy).

### LINKED ISSUE #379: fix race warning in vdisk_complete.go
```
==================
WARNING: DATA RACE
Write at 0x00c42013362c by goroutine 11:
  internal/race.Write()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/sync/waitgroup.go:129 +0x14b
  github.com/zero-os/0-Disk/nbd/nbdserver.(*vdiskCompletion).Wait()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/vdisk_complete.go:14 +0x3e
  github.com/zero-os/0-Disk/nbd/nbdserver.testBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:107 +0x72f
  github.com/zero-os/0-Disk/nbd/nbdserver.TestBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:73 +0x410
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
Previous read at 0x00c42013362c by goroutine 114:
  internal/race.Read()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/sync/waitgroup.go:71 +0x26b
  github.com/zero-os/0-Disk/nbd/nbdserver.(*vdiskCompletion).Add()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/vdisk_complete.go:29 +0x43
  github.com/zero-os/0-Disk/nbd/nbdserver.(*backend).GoBackground()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend.go:223 +0x128
Goroutine 11 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
  testing.runTests()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/zero-os/0-Disk/nbd/nbdserver/_test/_testmain.go:78 +0x20f
t=2017-08-08T14:27:34+0000 lvl=info msg="vdisk 'a' received SIGTERM" module=global caller=backend.go:239
Goroutine 114 (running) created at:
  github.com/zero-os/0-Disk/nbd/nbdserver.testBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:86 +0x2a7
  github.com/zero-os/0-Disk/nbd/nbdserver.TestBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:73 +0x410
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
==================
```

### PR DESCRIPTION
**Pull request by GlenDC**
+ fixes #379: I'm still not a big fan of the design around that feature, but for now it has to do, as we have bigger fish to fry;
+ moved gonbdserver race test to its own travis job, as it simply requires a lot of time (I think);
+ fixes #376: redesign LBA code;

### CODE REVIEW

File: nbd/ardb/storage/lba/sector.go [hunk 1]
```diff
@@ -82,12 +79,12 @@ func (s *sector) IsNil() bool {
...
 }
 
-func (s *sector) Write(w io.Writer) (err error) {
-	if s.IsNil() {
-		err = errNilSectorWrite
-		return
+// Bytes returns this sector's internal byte slice,
+// NOTE: this should never be used for non-storage purposes.
+func (s *sector) Bytes() []byte {
+	if s == nil || s.IsNil() {
```
Comment (iwanbk) [inline nbd/ardb/storage/lba/sector.go]: I think `s == nil` is not needed

Comment (GlenDC) [inline nbd/ardb/storage/lba/sector.go]: you're right, I don't think I ever pass in a `nil` sector to `storage.SetSector` in the bucket code, so I suppose that nil check will never be called. Will delete it.
