### PR TITLE
Remove sock read deadline

### LINKED ISSUE #260: TestReconnectFromRead test failed (once)
It only happened once locally, and I haven't seen it happen during travis (perhaps it's a new issue), but `github.com/zero-os/0-Disk/tlog/tlogclient`'s test `TestReconnectFromRead ` failed for me once today, during a `make testgo` run:

```
t=2017-06-08T11:57:12-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65235" module=global caller=redis.go:47
t=2017-06-08T11:57:12-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65236" module=global caller=redis.go:47
t=2017-06-08T11:57:12-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65237" module=global caller=redis.go:47
t=2017-06-08T11:57:12-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65238" module=global caller=redis.go:47
t=2017-06-08T11:57:12-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65239" module=global caller=redis.go:47
t=2017-06-08T11:57:12-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65240" module=global caller=redis.go:47
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65242 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65249 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=info msg="failed to send resp to :12345, err:writev tcp 127.0.0.1:65241->127.0.0.1:65249: use of closed network connection" module=global caller=server.go:297
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65250 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=info msg="failed to send resp to :12345, err:writev tcp 127.0.0.1:65241->127.0.0.1:65250: use of closed network connection" module=global caller=server.go:297
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65251 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65252 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=info msg="failed to send resp to :12345, err:writev tcp 127.0.0.1:65241->127.0.0.1:65252: use of closed network connection" module=global caller=server.go:297
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65253 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=eror msg="connection from 127.0.0.1:65254 dropped with an error: read tcp 127.0.0.1:65241->127.0.0.1:65254: read: connection reset by peer" module=global caller=server.go:107
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65255 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=info msg="failed to send resp to :12345, err:writev tcp 127.0.0.1:65241->127.0.0.1:65255: use of closed network connection" module=global caller=server.go:297
t=2017-06-08T11:57:12-0500 lvl=eror msg="connection from 127.0.0.1:65256 dropped with an error: read tcp 127.0.0.1:65241->127.0.0.1:65256: read: connection reset by peer" module=global caller=server.go:107
t=2017-06-08T11:57:12-0500 lvl=info msg="failed to send resp to :12345, err:writev tcp 127.0.0.1:65241->127.0.0.1:65256: use of closed network connection" module=global caller=server.go:297
t=2017-06-08T11:57:12-0500 lvl=info msg="connection from 127.0.0.1:65257 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:12-0500 lvl=info msg="failed to send resp to :12345, err:writev tcp 127.0.0.1:65241->127.0.0.1:65257: use of closed network connection" module=global caller=server.go:297
t=2017-06-08T11:57:17-0500 lvl=info msg="connection from 127.0.0.1:65258 dropped" module=global caller=server.go:105
t=2017-06-08T11:57:17-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65263" module=global caller=redis.go:47
t=2017-06-08T11:57:17-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65264" module=global caller=redis.go:47
t=2017-06-08T11:57:17-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65265" module=global caller=redis.go:47
t=2017-06-08T11:57:17-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65266" module=global caller=redis.go:47
t=2017-06-08T11:57:17-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65267" module=global caller=redis.go:47
t=2017-06-08T11:57:17-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:65268" module=global caller=redis.go:47
t=2017-06-08T11:57:17-0500 lvl=info msg="tlogclient : reconnect from read because of : read tcp 127.0.0.1:65270->127.0.0.1:65269: use of closed network connection" module=global caller=client.go:198
t=2017-06-08T11:57:17-0500 lvl=info msg="connection from 127.0.0.1:65270 dropped" module=global caller=server.go:105
--- FAIL: TestReconnectFromRead (9.02s)
	reconnect_test.go:86: TestReconnectFromRead failed : too long
t=2017-06-08T11:57:26-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:49205" module=global caller=redis.go:47
t=2017-06-08T11:57:26-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:49206" module=global caller=redis.go:47
t=2017-06-08T11:57:26-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:49207" module=global caller=redis.go:47
t=2017-06-08T11:57:26-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:49208" module=global caller=redis.go:47
t=2017-06-08T11:57:26-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:49209" module=global caller=redis.go:47
t=2017-06-08T11:57:26-0500 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:49210" module=global caller=redis.go:47
t=2017-06-08T11:57:31-0500 lvl=info msg="tlogclient : reconnect from read because of : EOF" module=global caller=client.go:198
FAIL
FAIL	github.com/zero-os/0-Disk/tlog/tlogclient	19.096s
```

### PR DESCRIPTION
**Pull request by iwanbk**
Fixes #260.

The problem was caused by `SetReadDeadline`, not sure why, maybe capnp decoder doesn't work well with it.

It was added to avoid the deadlock on the reader side.

The solution is to use `CloseRead` https://golang.org/pkg/net/#TCPConn.CloseRead to interrupt the reader.

### CODE REVIEW

File: tlog/tlogclient/client.go [hunk 1]
```diff
@@ -97,6 +106,10 @@ func (c *Client) reconnect(closedTime time.Time) (err error) {
 
 // connect to server
 func (c *Client) connect(firstSequence uint64, resetFirstSeq bool) (err error) {
+	if c.conn != nil {
+		c.conn.CloseRead() // interrupt the receiver
```
Comment (GlenDC) [inline tlog/tlogclient/client.go]: Why not do `c.conn.Close()`?

File: tlog/tlogclient/client.go [hunk 2]
```diff
@@ -380,19 +393,27 @@ func (c *Client) sendReconnect(sender func() (interface{}, error)) (interface{},
...
-	return nil, err
+	return nil, errMaxSendRetry
 }
 
 // Close the open connection, making this client invalid.
 // It is user responsibility to call this function.
 func (c *Client) Close() error {
+	c.stopped = true
+	if c.conn != nil {
+		c.conn.CloseRead() // interrupt the receiver
```
Comment (GlenDC) [inline tlog/tlogclient/client.go]: Why not do c.conn.Close()?

File: tlog/tlogclient/client.go [hunk 3]
```diff
@@ -380,19 +393,27 @@ func (c *Client) sendReconnect(sender func() (interface{}, error)) (interface{},
...
 
 	c.wLock.Lock()
 	defer c.wLock.Unlock()
 
 	c.rLock.Lock()
-	c.rLock.Unlock()
+	defer c.rLock.Unlock()
 
-	return c.conn.Close()
+	if c != nil {
```
Comment (GlenDC) [inline tlog/tlogclient/client.go]: Should be `c.conn != nil`, no?

File: tlog/tlogclient/client.go [hunk 4]
```diff
@@ -380,19 +393,27 @@ func (c *Client) sendReconnect(sender func() (interface{}, error)) (interface{},
...
+		return c.conn.Close()
```
Comment (GlenDC) [inline tlog/tlogclient/client.go]: should you then also not do `c.conn = nil`, before you return the close `error`?

File: tlog/tlogclient/client.go [hunk 5]
```diff
@@ -58,6 +63,7 @@ type Client struct {
 	cancelFunc context.CancelFunc
 
 	lastConnected time.Time
+	stopped       bool
```
Comment (GlenDC) [inline tlog/tlogclient/client.go]: I don't think you need a separate `stopped` variable, do you? Couldn't you just assign `nil` to `c.conn`, and simply do a `c.conn == nil` check instead of `c.stopped == false`?

Comment (iwanbk) [inline tlog/tlogclient/client.go]: some goroutine might still use the `conn`

File: tlog/tlogclient/client.go (hunk 1 above)
Comment (iwanbk) [inline tlog/tlogclient/client.go]: because we only want to interrupt the receiver here

File: tlog/tlogclient/client.go (hunk 2 above)
Comment (iwanbk) [inline tlog/tlogclient/client.go]: Same as previous comment.
`Close` might work, but we need to test it.

File: tlog/tlogclient/client.go (hunk 3 above)
Comment (iwanbk) [inline tlog/tlogclient/client.go]: my bad, fixed

File: tlog/tlogclient/client.go (hunk 4 above)
Comment (iwanbk) [inline tlog/tlogclient/client.go]: No, GC will do it for us
