### PR TITLE
Fix force flush race

### LINKED ISSUE #228: Add optional sequence param to tlog ForceFlush
See https://github.com/g8os/blockstor/issues/188#issuecomment-304852303

> 
> Was thinking about adding optional sequence param to the force flush command. Was not sure that it is useful, but i'm sure that it is useful now.
> 
> If specified, the tlog server needs to wait until it have the given sequence in (ready to) flush buffer before doing the force flush.
> (in current implementation, force flush means doing the flush right now).

### PR DESCRIPTION
**Pull request by iwanbk**
Closes #228

### CODE REVIEW

File: tlog/tlogserver/server/common_test.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+import (
+	"testing"
+
+	"github.com/zero-os/0-Disk/tlog"
+)
+
+func createTestServer(t *testing.T, flushTime int) (*Server, *Config, error) {
+	conf := DefaultConfig()
+	conf.ListenAddr = "127.0.0.1:0"
```
Comment (GlenDC) [inline tlog/tlogserver/server/common_test.go]: I've said this before, but you can simply set it empty, `conf.ListenAddr = ""`, will achieve you the same, except that it will also support IPv6 if available. And you know, it's shorter to type 💃

File: tlog/tlogserver/server/vdisk.go [hunk 2]
```diff
@@ -363,14 +365,13 @@ func (vd *vdisk) runFlusher() {
 			switch cmdType {
 			case vdiskCmdForceFlushAtSeq:
 				seqToForceFlush = flusherCmd.sequence
-				if vd.expectedSequence <= seqToForceFlush { // we don't have it yet
+				if maxSeq < seqToForceFlush { // we don't have it yet
```
Comment (GlenDC) [inline tlog/tlogserver/server/vdisk.go]: seems like you can refactor this to `needForceFlushSeq = maxSeq < seqToForceFlush`, no?

Comment (GlenDC) [inline tlog/tlogserver/server/vdisk.go]: Ahno, wait nevermind. The more important one is the continue statement, as to not flush, so nevermind my comment :| *hides*
